export enum Counties {
	CARLOW = 'Carlow',
	CAVAN = 'Cavan',
	CLARE = 'Clare',
	CORK = 'Cork',
	DONEGAL = 'Donegal',
	DUBLIN_CITY = 'Dublin City',			// Dublin
	DL_RATHDOWN = 'Dun Laoghaire-Rathdown',	// Dublin
	FINGAL = 'Fingal',						// Dublin
	SOUTH_DUBLIN = 'South Dublin',			// Dublin
	GALWAY = 'Galway',
	KERRY = 'Kerry',
	KILDARE = 'Kildare',
	KILKENNY = 'Kilkenny',
	LAOIS = 'Laois',
	LEITRIM = 'Leitrim',
	LIMERICK = 'Limerick',
	LONGFORD = 'Longford',
	LOUTH = 'Louth',
	MAYO = 'Mayo',
	MEATH = 'Meath',
	MONAGHAN = 'Monaghan',
	OFFALY = 'Offaly',
	ROSCOMMON = 'Roscommon',
	SLIGO = 'Sligo',
	TIPPERARY = 'Tipperary',
	WATERFORD = 'Waterford',
	WESTMEATH = 'Westmeath',
	WEXFORD = 'Wexford',
	WICKLOW = 'Wicklow',
}
